### ISSUE TITLE
Prep for open source

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/pre-selector#10]
## TODO (in order)

- [ ] Add PR / Issue templates (`.yaml` instead of `.md`?)
- [ ] Reset `main` in to initial commit and do things right (when prototyping is done)?
- [ ] [Add GitHub community files?](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types)
- [ ] [Protect the `main` branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)
- [ ] [Finish up `README.md`](https://github.com/tox-dev/pipdeptree)
  - [ ] [Requirements / setup](https://github.com/tiangolo/fastapi#requirements)
  - [ ] Add instructions / showcase
    - [ ] [Add YT video](https://www.youtube.com/watch?v=CY05nUQ4D5M)
    - [ ] Add [asciinema](https://asciinema.org/) GIF
    - [ ] A written one
      - [ ] Add Windows counterparts for venv commands
      - [ ] Move venv commands from 'dev' to 'instructions' / 'setup'
- [ ] Add standards and enforce them (linting, formatting, git commit msgs, pr titles etc.)
  - [**GitHub Actions**](https://github.com/features/actions)
  - [**pre-commit**](https://pre-commit.com/) / [**pre-commit.ci**](https://pre-commit.ci)
    - Add info to README.md
    - Check if everything installs on other machines
    - Implement
      - Safe guards (local branch protection, etc.)
      - Formatting (`black`)
      - Testing?
      - Publishing?
- [ ] CI / CD pipelines ([**pip**](https://pypi.org/project/pip/) deploy)
  - [ ] Testing
  - [ ] Publishing

## Resources

- [Nicer Project Description](https://pypi.org/project/pipdeptree/)
- [Setting Up An Open Source Project](https://github.com/KatherineMichel/setting-up-an-open-source-project)
