### ISSUE TITLE
Add `helpers.py` files

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/pre-selector#14]
## TODO

- [ ] Move funcs:
  - [ ] clearing term
  - [ ] checking if path points to file or not
  - [ ] checking if git repo / getting root dir
  - [ ] checking if arg was given (or not, it's just for prototyping)
