### ISSUE TITLE
Final tests / stuff

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/pre-selector#2]
## TODO

- [ ] Make sure the script gets all extensions
- [ ] Fix up things like missing descriptions and so on in `hook_ext_pairs` (from `hooks.json`)
- [ ] Add spinner animations?
- [ ] Error catching + clear messages
  - [ ] internet connectiong for update check scripts
- [ ] Make sure it works on other OSs

## Resources
