### ISSUE TITLE
Implement modes

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/pre-selector#3]
## Description

Implement the 2 modes of interacting with the program (users will be able to pick them from the menu).

## TODO

- [ ] Select everything by yourself mode (language / name and such)
  - [ ] Show detected ext to ease the process? (do so by highlighting certain hook groups?)
  - [ ] Add a search function and pick by checking off a group? (this will then get printed in to an MD file to pick the exact hooks)
- [ ] Auto select the language ones by detecting ext and than add additional ones yourself
  - [ ] Figure out the exact process (step by step)
  - [ ] Figure out better approach to getting file extensions
    - [ ] Count amount of each file?
    - [ ] Only get files that aren't in `.gitignore`
      - [ ] `git ls-files` (BUT everything needs to be at least staged - check out command options?)
      - [ ] exclude files like `.gitignore` itself and other git files
      - [ ] <https://waylonwalker.com/python-git/>
      - [ ] <https://unix.stackexchange.com/a/358286>
      - [ ] <https://stackoverflow.com/a/51170709/11749019>
      - [ ] <https://gitpython.readthedocs.io/en/0.3.5/tutorial.html>
    - [ ] Figure out edge cases
      - [ ] `run` / `artisan` (no ext) try getting from shebang?
      - [ ] `.env.testing` / `.add.spl` (combined ext)
      - [ ] `.gitattribute` (file names that are the ext)

## Resources
