### ISSUE TITLE
Implement update checking

### ISSUE THREAD

**Issue by ErykDarnowski** [ErykDarnowski/pre-selector#9]
## Description

Check whether the hooks list on [**pre-commit**]()'s wesbite changed (were updated).

## TODO

- [ ] Show status in `menu.py`?
- [ ] Check if program had new release
- [ ] Add diff view of updated file display?
  - sh pkg + `diff`?
  - [difflib — Helpers for computing deltas](https://docs.python.org/3/library/difflib.html)
